name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore TransactionsService/TransactionsService.csproj

    - name: Restore test project dependencies
      run: dotnet restore tests/Transactions.UnitTests/Transactions.UnitTests.csproj

    - name: Build solution
      run: dotnet build TransactionsService/TransactionsService.csproj --configuration Release

    - name: Build test project
      run: dotnet build tests/Transactions.UnitTests/Transactions.UnitTests.csproj --configuration Release

    - name: Run tests
      run: dotnet test tests/Transactions.UnitTests/Transactions.UnitTests.csproj --configuration Release --no-build --verbosity normal

    # bypass to integrate with docker hub free account
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # extract unique tag
    - name: Extract short SHA
      id: vars
      run: echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV        

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./TransactionsService
        file: ./TransactionsService/Dockerfile
        push: true        
        tags: |
          devpraxis/transactions-service:latest
          devpraxis/transactions-service:${{ env.GIT_SHA_SHORT }}        
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
